[package]
name = "shopify_customer_account"
version = "0.1.0"
edition = "2024"
authors = ["Torben A. Flessner <git@flessner.dev>"]
description = "Client for the Shopify Customer Account API"
repository = "https://github.com/flessner/shopify-rs"
license = "MIT OR Apache-2.0"

[dependencies]
cynic = { version = "3", features = ["http-reqwest"] }
reqwest = { version = "0.13", default-features = false, features = [
    "json",
    "rustls",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["sync"] }

[build-dependencies]
cynic-codegen = "3"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
